xflags::xflags! {
    src "./src/flags.rs"

    cmd os_installer {
        default cmd help {
            optional -h, --help
        }

        /// Only install the packages
        cmd install-packages {
        }
    }
}
// generated start
// The following code is generated by `xflags` macro.
// Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
#[derive(Debug)]
pub struct Os_installer {
    pub subcommand: Os_installerCmd,
}

#[derive(Debug)]
pub enum Os_installerCmd {
    Help(Help),
    InstallPackages(InstallPackages),
}

#[derive(Debug)]
pub struct Help {
    pub help: bool,
}

#[derive(Debug)]
pub struct InstallPackages;

impl Os_installer {
    pub const HELP: &'static str = Self::HELP_;

    pub fn from_env() -> xflags::Result<Self> {
        Self::from_env_()
    }

    pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
        Self::from_vec_(args)
    }
}
// generated end
